# network architecture
# encoder related
encoder: contextual_block_transformer
encoder_conf:
    output_size: 400    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder architecture type
    normalize_before: true
    block_size: 24
    hop_size: 10
    look_ahead: 4
    init_average: true
    ctx_pos_enc: true

# decoder related
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 1024
    embed_dim: 300
    sampling_probability: 0.0   # scheduled sampling option
    dropout: 0.0
    att_conf:
        atype: MoChA
        awin: 10
        adim: 512


# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false
    loss_type: CE

# minibatch related
# batch_type: numel
batch_size: 24 
# batch_bins: 1700000

# optimization related
accum_grad: 2
grad_clip: 5
patience: 10
max_epoch: 2
num_iters_per_epoch: 60000
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: !!float 1e-5

scheduler: reducelronplateau
scheduler_conf:
    mode: max
    factor: 0.5
    patience: 0

# specaug: specaug
# specaug_conf:
#     apply_time_warp: true
#     time_warp_window: 5
#     time_warp_mode: bicubic
#     apply_freq_mask: true
#     freq_mask_width_range:
#     - 0 
#     - 30 
#     num_freq_mask: 2 
#     apply_time_mask: true
#     time_mask_width_range: 
#     - 0 
#     - 40
#     num_time_mask: 2
#     utt_apply_prob: 1.0


# transfer learning
pretrain_path: [
    ../2w4-data-rvb0.2/exp/asr_train_asr_cbp_transformer400_RNN_1024x1_L40C40R16_fbank_pitch_char/valid.acc.best.pth,
    ]
pretrain_key: [null]
